---
- name: detector for Apache Log4j (CVE-2021-44228)
  hosts: all
  become: true
  tasks:
    - include_vars: vars.yml

    - name: dependency present
      ansible.builtin.package:
        name:
          - unzip
          - gpg
          - dirmngr
          - file
        state: present
        update_cache: true

    - name: create detector directory
      ansible.builtin.file:
        path: '{{ detector_dir }}'
        state: directory

    - name: download detector file
      ansible.builtin.get_url:
        url: "{{ detector_baseurl }}{{ sh_detector }}"
        dest: "{{ detector_dir }}{{ sh_detector }}"
        mode: '0755'
        owner: root
        group: root

    - name: download detector signature
      ansible.builtin.get_url:
        url: "{{ detector_baseurl }}{{ sh_signature }}"
        dest: "{{ detector_dir }}{{ sh_signature }}"
        mode: '0644'
        owner: root
        group: root
      when: verify_gpg

    - name: gpg public key
      ansible.builtin.command: '{{ gpg_public_key }}'
      when: verify_gpg

    - name: gpg verify detector
      ansible.builtin.command: >-
        gpg --verify {{ detector_dir }}{{ sh_signature }} {{ detector_dir }}{{ sh_detector }}
      when: verify_gpg

    - name: remove any detector run directory
      ansible.builtin.file:
        path: '{{ detector_dir }}{{ detector_run_dir }}'
        state: absent
      when: clean_run_before

    - name: create detector run directory
      ansible.builtin.file:
        path: '{{ detector_dir }}{{ detector_run_dir }}'
        state: directory

    - name: run detector/scanner
      ansible.builtin.command: >-
        {{ detector_dir }}{{ sh_detector }} {{ detector_options }} --tmp {{ detector_dir }}{{ detector_run_dir }}

    - name: files in detector run directory
      ansible.builtin.find:
        paths: '{{ detector_dir }}{{ detector_run_dir }}'
      register: vulnerable

    - name: print vulnerable path(s) found
      ansible.builtin.debug:
        var: vulnerable

    - name: remove detector directory
      ansible.builtin.file:
        path: '{{ detector_dir }}'
        state: absent
      when: delete_after
